import { z } from "zod";
import type { NextRequest } from "next/server";
import { requireUser } from "@/lib/api";
import { audit } from "@/lib/audit";
import { createGiteaTemplateProposal, GiteaApiError, isRuntimeConfigurationError } from "@/lib/gitea";
import { ensureStudyGiteaWorkspace } from "@/lib/gitea-workspaces";
import { json, problem } from "@/lib/json";
import {
  buildTemplateRepositoryFiles,
  templateKeyForName,
  templateRepoName,
  validateTemplateIntake,
  validateTemplateRepositoryFiles,
  type TemplateIntakeAnswers
} from "@/lib/pipeline-template-code";
import { prisma } from "@/lib/prisma";
import { assertStudyAccess, isForbiddenError } from "@/lib/rbac";
import { slugify } from "@/lib/slug";

const intakeSchema = z.object({
  purpose: z.string().trim().min(3),
  clinicalUseCase: z.string().trim().min(3),
  dataModalities: z.array(z.string().trim().min(1)).min(1),
  siteLocalInputs: z.string().trim().min(3),
  syntheticFixtures: z.string().trim().min(3),
  nvflareWorkflow: z.string().trim().min(3),
  minClients: z.coerce.number().int().min(1),
  numRounds: z.coerce.number().int().min(1),
  aggregation: z.string().trim().min(3),
  privacyConstraints: z.string().trim().min(3),
  dependencyPolicy: z.string().trim().min(3),
  artifactOutputs: z.string().trim().min(3),
  reviewExpectations: z.string().trim().min(3)
});

const createSchema = z.object({
  name: z.string().trim().min(3).max(200),
  description: z.string().trim().max(2000).optional(),
  prompt: z.string().trim().min(20).max(12000),
  intakeAnswers: intakeSchema
});

type Params = { params: Promise<{ studyId: string }> };

export async function GET(_request: NextRequest, { params }: Params) {
  const authResult = await requireUser();
  if ("response" in authResult) return authResult.response;
  const { studyId } = await params;

  try {
    await assertStudyAccess(authResult.userId, studyId, "read");
  } catch (error) {
    if (isForbiddenError(error)) return problem(403, error.message, "forbidden");
    throw error;
  }

  const templates = await prisma.pipelineTemplate.findMany({
    where: { studyId, scope: "STUDY_TEMPLATE", active: true },
    include: {
      currentApprovedVersion: true,
      templateVersions: { orderBy: { createdAt: "desc" } },
      templateProposals: { orderBy: { createdAt: "desc" }, take: 10 },
      sourceTemplate: { select: { id: true, name: true, templateKey: true, giteaRepoUrl: true } }
    },
    orderBy: { updatedAt: "desc" }
  });

  return json({ templates });
}

export async function POST(request: NextRequest, { params }: Params) {
  const authResult = await requireUser();
  if ("response" in authResult) return authResult.response;
  const { studyId } = await params;

  try {
    await assertStudyAccess(authResult.userId, studyId, "runAgent");
  } catch (error) {
    if (isForbiddenError(error)) return problem(403, error.message, "forbidden");
    throw error;
  }

  const parsed = createSchema.safeParse(await request.json());
  if (!parsed.success) return problem(400, parsed.error.issues[0]?.message ?? "Invalid study template request.");

  const intakeErrors = validateTemplateIntake(parsed.data.intakeAnswers as TemplateIntakeAnswers);
  if (intakeErrors.length > 0) return problem(400, intakeErrors.join(" "), "template_intake_incomplete");

  const templateKey = templateKeyForName(parsed.data.name);
  const files = await buildTemplateRepositoryFiles({
    name: parsed.data.name,
    templateKey,
    description: parsed.data.description,
    prompt: parsed.data.prompt,
    intake: parsed.data.intakeAnswers as TemplateIntakeAnswers
  });
  const validation = validateTemplateRepositoryFiles(files);
  if (validation.status !== "PASSED") return problem(422, validation.summary, "template_validation_failed");

  let workspace;
  let gitea;
  try {
    workspace = await ensureStudyGiteaWorkspace({ studyId, userId: authResult.userId });
    gitea = await createGiteaTemplateProposal({
      owner: workspace.owner,
      repoName: templateRepoName(parsed.data.name),
      templateName: parsed.data.name,
      description: parsed.data.description ?? `Study-private NVFLARE template: ${parsed.data.name}`,
      branchName: `fedlify/template-${slugify(parsed.data.name).slice(0, 42)}-${Date.now().toString(36)}`,
      files,
      pullRequestBody: [
        `Study-private template: ${parsed.data.name}`,
        "",
        "This draft pull request was generated by the Fedlify template agent workflow.",
        "",
        validation.summary
      ].join("\n")
    });
  } catch (error) {
    if (isRuntimeConfigurationError(error)) return problem(503, error.message, "gitea_not_configured");
    if (error instanceof GiteaApiError) return problem(502, error.message, "gitea_api_error");
    throw error;
  }

  const result = await prisma.$transaction(async (tx) => {
    const template = await tx.pipelineTemplate.create({
      data: {
        name: parsed.data.name,
        templateKey,
        scope: "STUDY_TEMPLATE",
        studyId,
        framework: "nvflare",
        description: parsed.data.description,
        version: "1.0.0",
        spec: parsed.data.intakeAnswers,
        active: true,
        status: "VALIDATED",
        giteaOwner: gitea.owner,
        giteaRepo: gitea.repo,
        giteaRepoUrl: gitea.repoUrl,
        giteaDefaultBranch: gitea.baseBranch,
        createdById: authResult.userId
      }
    });

    const proposal = await tx.templateProposal.create({
      data: {
        templateId: template.id,
        requestedById: authResult.userId,
        kind: "NEW_TEMPLATE",
        intakeAnswers: parsed.data.intakeAnswers,
        prompt: parsed.data.prompt,
        branchName: gitea.branchName,
        giteaPullRequestUrl: gitea.pullRequestUrl,
        giteaPullRequestNumber: gitea.pullRequestNumber,
        giteaHeadCommit: gitea.commitSha,
        giteaBaseBranch: gitea.baseBranch,
        status: "OPEN",
        validationStatus: "PASSED",
        resultSummary: validation.summary
      }
    });

    return { template, proposal };
  });

  await audit({
    actorUserId: authResult.userId,
    studyId,
    action: "study_template.create",
    targetType: "PipelineTemplate",
    targetId: result.template.id,
    metadata: {
      giteaRepo: `${gitea.owner}/${gitea.repo}`,
      giteaPullRequestNumber: gitea.pullRequestNumber,
      gitCommit: gitea.commitSha
    },
    request
  });

  return json(result, { status: 201 });
}
